### ISSUE TITLE
Compared to tsserver within vscode? 

### ISSUE THREAD

**Issue by midzelis** [sourcegraph/javascript-typescript-langserver#225]
How does this language server compare with [tsserver](https://github.com/Microsoft/TypeScript/blob/master/lib/tsserver.js) within vscode?

**Comment by felixfbecker** [comment]
Hey @midzelis, I will do a readme update soon. The aim is feature parity with tsserver. The primary benefit right now is for editors that support LSP because they don't need to implement the tsserver protocol.

There are some more features, hovers look a bit different: https://github.com/sourcegraph/javascript-typescript-langserver/pull/236
And we support LSP methods and extensions that are not part of the tsserver protocol and allow more advanced analysis.
In addition, the LS can run isolated (not access the local file system) and serve multiple clients over TCP.
