### ISSUE TITLE
getWorkspaceFiles fails to return files on Windows

### ISSUE THREAD

**Issue by tomv564** [sourcegraph/javascript-typescript-langserver#250]
The service is unable to respond to any request as the structure could not be loaded from the LocalFileSystem - no files are returned from **glob** as the `cwd` is parameter is malformed.

The server is initialized with rootUri `file:///C:/Users/tvanommeren/Projects/myproject`

The problem appears around https://github.com/sourcegraph/javascript-typescript-langserver/blob/master/src/fs.ts#L67
where rootPath is `C:/Users/tvanommeren/Projects/myproject`
which is turned into `file:////C%3A/Users/tvanommeren/Projects/myproject` by **path2uri**
and then back into `\\C:\Users\tvanommeren\Projects\myproject` by **resolveUriToPath**

baseUri becomes `file://///C%3A/Users/tvanommeren/Projects/myproject`

Changing the aforementioned line to this fixes the issue:
```
const root = base ? this.resolveUriToPath(base) : this.rootPath;
```

**Comment by felixfbecker** [comment]
The URI <-> file conversion is the thing about this LS that I hate the most and I tried multiple times to overhaul it...
A PR with a failing test and/or fix would be appreciated

**Comment by tomv564** [comment]
Yes, this part of the code is not becoming clearer unfortunately.

I think the extra number of slashes on baseUri is caused by the new logic at https://github.com/sourcegraph/javascript-typescript-langserver/blob/4f678e7809408ac44cc46eb12a662cff312f06fd/src/util.ts#L110-L112

I'll test the fixes locally and send fixes + tests early next week.

Another option is to run an integration test on each platform - the Windows problems so far would have been found just by starting the service and making a hover query.

**Comment by felixfbecker** [comment]
I added testing with a Windows path already, but there is the global `setStrict` which I wanted to remove for a while now, see #99

**Comment by felixfbecker** [comment]
I think `path2uri` is to blame here. I tried changing its algorithm multiple times now to return correct Windows paths, but it always broke language features, I assume because many methods atm depend on Unix paths.

**Comment by tomv564** [comment]
Does the optional base parameter in getWorkspaceFiles need to be implemented? I don't see it used anywhere for either filesystem, and it would greatly simplify the implementation for now.

**Comment by felixfbecker** [comment]
Not for our current usage, it was used originally and is now there for spec conformance. Spec says if `base` is not specified it defaults to the `rootUri`, so I don't think the implementation would be that simpler.

**Comment by tomv564** [comment]
Just realised `setStrict(true)` was being set for all tests "to make them pass on Windows".
As the current testing is not going to give Windows users any guarantees, I'm interested in taking a stab at removing the OS-specific logic. 

I have some suggestions to reduce complexity in these areas, would love your feedback:
* Could LocalFileSystem's `resolveUriToPath` be made private?
  * The comment in fs.ts:66 demands resolveUriToPath be called in case it's overridden 
  * getWorkspaceFiles then doesn't _have_ to round-trip a perfectly valid rootPath to URI and back if `base` is not provided
* `path2uri` takes an optional-ish `root` parameter which is often defaulted with '' to handling joining paths, while the "real" `rootPath` is passed into the second parameter, named `file`.
  * Could we remove 1 parameter and made callers responsible for joining paths?

**Comment by felixfbecker** [comment]
Yes, I even opened an issue for this: #99

1. No, we override it in Sourcegraph because we need to handle dependency installation. But I think a solution here would be to not pass the `rootPath`, but the `rootUri` to the constructor.
2. Yes, I hate that function. There is a point to be made in favour for having a rootUri param because without it you can only infer the scheme as `file:` which may not be true. But in it's current form it's just a pure violation of SoC.

Here are some more thoughts I had:
- Currently, the internals of the LS and TS always work with Unix style paths. E.g. even on Windows `C:\foo` is internally handled as `/c:/foo`. I tried to change `uri2path` to return the former instead, but tests began failing and I couldn't figure out why. My thought was that TS _should_ be able to work with Windows paths, but maybe that's not true. This is why I added a second function `uriToLocalPath` which guarantees to give you a Windows path for a Windows `file:` URI and should be used in LocalFileSystem.
- `path2uri` behaves differently depending on two conditions: the host OS and "strict mode".
  - There is no real reason why an LS could not run on Linux (e.g. in a Docker container) but gets Windows paths from the client. Therefor there should no special behaviour for the host OS, if any it should be done by inspecting the incoming path.
  - There is no reason why URIs and paths should be handled one way in "strict mode" and another in non-strict mode.

I would applaud you if you manage to clean this up, it is the thing about this codebase I dislike the most.

**Comment by tomv564** [comment]
This is starting to feel like a Sourcegraph issue to fix :)

In general, I would really love it if some of the sourcegraph
extensions/wishes were abstracted in a way so that the editor plugin user
does not pay for it (in performance or instability).

**Comment by felixfbecker** [comment]
Well, as I said, I already tried refactoring this logic multiple times, for example https://github.com/sourcegraph/javascript-typescript-langserver/pull/203/files#diff-8cd4968b81985f0efc2053eabc37db6dR101. But that is nothing Sourcegraph specific, I care a lot about adding no code to the language server that couples it to a specific client - which is why we use inheritance to implement the special use cases and only implement here what would be useful for other clients too. Are you referring to anything specific?

**Comment by tomv564** [comment]
I should have clarified: Your previous response included two statements (we can't assume file:// uris and we can't assume server OS = client OS) that made me worry about my ability to fix Windows paths.

So many tests in the WHATWG PR, what is needed to get that merged first?

**Comment by tomv564** [comment]
I did a bunch of the work for #260 on Windows and this issue has not reappeared ( I think your earlier fix already took care of it). We might be ready to close this issue after merging that PR.

**Comment by felixfbecker** [comment]
Thanks for the awesome work!
