### ISSUE TITLE
Switch from legacy fs extension to new files extension

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/javascript-typescript-langserver#77]
The old `fs/readFile` extension should be replaced by the new `workspace/files`, `textDocument/content` extension.

https://github.com/sourcegraph/language-server-protocol/blob/master/extension-files.md

**Comment by beyang** [comment]
This could yield a substantial performance boost, as you'd brought up earlier. Instead of having to do successive `readDir` requests, it just does one `workspace/xfiles` request on initialization. It might significantly simplify the code associated with mirroring the remote filesystem structure locally.
